// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function App(Props) {
  return React.createElement("div", {
              className: "bg-gray-500 p-8 text-gray-100 text-2xl text-center"
            }, "Hei, verden!");
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
