// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as App$RescriptViteReactWindicss from "./App.bs.js";

var root = document.querySelector("#app");

if (!(root == null)) {
  ReactDom.render(React.createElement(App$RescriptViteReactWindicss.make, {}), root);
}

export {
  
}
/* root Not a pure module */
